SQLALCHEMY_ECHO = True

SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://msn_mmais:msn123@localhost/msntooldb_dev'

SQLALCHEMY_TRACK_MODIFICATIONS = False

SQLALCHEMY_ENCODING = "utf8"

SQLALCHEMY_POOL_TIMEOUT = 15

SQLALCHEMY_POOL_RECYCLE = 2